name: CI
on: [push]
jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v1 # or alternative dependency management
      - uses: php-actions/phpunit@v9

  unit-tests:
    - name: PHPUnit tests
      uses: php-actions/phpunit@v9
      with:
        configuration: backend_web/phpunit.xml.dist
        memory_limit: 256M