name: CI
on: [push]
jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['7.4.10']
    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: intl #optional
          ini-values: "post_max_size=256M" #optional
          tools: composer:v2
      - name: System dependencies
        run: |
          sudo apt-get install -y whois
          sudo apt-get install -y host
      - name: Check PHP Version
        run: php -v
      - name: Which php
        run: which php
      - name: Composer Install en backend_web
        run: |
          cd backend_web
          composer install
          ls
      - name: Run phpunit exampletest
        run: |
          pwd
          cd backend_web
          # cat ./tests/ExampleTest.php
          # php ./vendor/bin/phpunit ./tests/ExampleTest.php > result.txt
          php vendor/bin/phpunit tests > result.txt
          cat result.txt